name: Test pushes and runners

on:
  push:
    branches: [ "master" ]

jobs:
  test:
    runs-on: self-hosted
	
    steps:
    - name: Checkout Repo
    - uses: actions/checkout@v4

    - name: Install sshpass
    run: sudo apt-get install -y sshpass

    - name: SSH into windows server
    run: |
      sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh-o StrictHostKeyChecking=no server@192.168.1.14 "npm run dev /mnt/c/users/server/documents/servedtunnels/reactaishoppinglist"
    env:
      SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
