name: Stop, Build & Run updated container

on:
  push:
    branches: [ "master" ]

jobs:
  stop_build_run:
    runs-on: self-hosted
    env:
      IMAGE_NAME: reactaishoppinglist
      PORT: 4444
      DIR: c:\users\server\documents\servedtunnels\reactaishoppinglist

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      #- name: Change to DIR
        #run: cd c:\users\server\documents\servedtunnels\${{env.IMAGE_NAME}}
      - name: Shut down current container
        run: docker stop $(docker ps -q --filter "ancestor=${{env.IMAGE_NAME}}")
      - name: Build new container
        run: docker build -t artimusmaximus/${{env.IMAGE_NAME}}:latest ${{env.DIR}}
      - name: Start new container
        run: docker run -d -p ${{env.PORT}}:${{env.PORT}} artimusmaximus/${{env.IMAGE_NAME}}:latest
